### ISSUE TITLE
generate CDS error

### ISSUE THREAD

**Issue by jackhu3301** [lonelycrab888/BiooBang#2]
![image](https://github.com/user-attachments/assets/41ae7464-8b16-45aa-81c3-f1a0e59e2ead)
Pls help me , thank you very much. All the things have done with your requirements.

**Comment by jackhu3301** [comment]
load pretrained model!
UniBioseqForCausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
start generation!
Traceback (most recent call last):
  File "/data/mRNA/BiooBang/generate_CDS.py", line 62, in <module>
    main()
  File "/data/mRNA/BiooBang/generate_CDS.py", line 53, in main
    result = model.generate(input_ids, max_length = max_length, num_beams = num_beams, logits_processor=logits_processor, low_memory=True, num_return_sequences=1)
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/generation/utils.py", line 2283, in generate
    result = self._beam_search(
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/generation/utils.py", line 3496, in _beam_search
    outputs_per_sub_batch = [
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/generation/utils.py", line 3497, in <listcomp>
    self(**inputs_per_sub_batch, return_dict=True) for inputs_per_sub_batch in inputs_per_sub_batches
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/mRNA/BiooBang/model/modeling_UniBioseq.py", line 759, in forward
    outputs = self.model(
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/mRNA/BiooBang/model/modeling_UniBioseq.py", line 569, in forward
    past_key_values = DynamicCache.from_legacy_cache(past_key_values, self.config.is_prefix_decoder, self.config.is_clm)
  File "/data/mRNA/BiooBang/model/UBL_utils/cache_utils.py", line 118, in from_legacy_cache
    cache = cls()
  File "/data/mRNA/BiooBang/model/UBL_utils/cache_utils.py", line 18, in __init__
    self.seen_tokens = 0  # Used in `generate` to keep tally of how many tokens the cache has seen
  File "/data/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1788, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute

**Comment by lonelycrab888** [comment]
I’m glad you’re interested in our work! What version of the transformers library are you using?

**Comment by lonelycrab888** [comment]
> I’m glad you’re interested in our work! What version of the transformers library are you using?

You can check using
```
import transformers

print(transformers.__version__)
```

**Comment by jackhu3301** [comment]
use transformers-4.47.1, the latest version not work. Then I tried 4.36.2, it works well.  Maybe some error with the latest version of transformers

**Comment by lonelycrab888** [comment]
> use transformers-4.47.1, the latest version not work. Then I tried 4.36.2, it works well. Maybe some error with the latest version of transformers

You are RIGHT. Currently, higher versions of the Transformers library do not support our model. Due to changes in our model architecture, its generation method differs from traditional GPT-like models. We explicitly modified some generation components, which might be the direct cause of the errors in higher versions. We plan to address this issue in the future to make its dependencies more general.

**Comment by jackhu3301** [comment]
Thank you so much
